### ISSUE TITLE
There is something wrong  copying the folder

### ISSUE THREAD

**Issue by sandogeek** [garethflowers/atom-portable#11]
thanks for your job.When I copy the folder to another position on Windows7,it shows up a window  named target path too long,I think it may be caused by node_module folder,there are a lot of folder in it.I try to zip it,but another similar problem occur.How can I solve this?

**Comment by garethflowers** [comment]
This is a known problem at the moment. It's due to the number of nested modules that is used by Node inside the application, making the paths to long when extracting the application.

The current workaround is too install/extract the application in to a location with a short a path as possible (i.e. in `C:\`).

I'm currently investigating a fix.

**Comment by garethflowers** [comment]
Recent versions of Atom have less nested directories inside `node_modules` and should not suffer this problem any more.
